### PR TITLE
Use leiningen to generate pom file for snyk

### PR DESCRIPTION
**Pull request by kevindiu**
Since snyk does not support clojure, this PR applied this workaround to generate the pom file for snyk to scan vulnerability.
https://support.snyk.io/hc/en-us/articles/360016431777-Clojure-Projects

It works in my local environment using `snyk` command.
```
$ snyk test

Testing ...../vdaas/vald-client-clj...

Organization:      kevindiu
Package manager:   maven
Target file:       pom.xml
Project name:      vald-client-clj:vald-client-clj
Open source:       no
Project path:      ....../vdaas/vald-client-clj
Licenses:          enabled

✔ Tested 29 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

```

Signed-off-by: kevindiu <kevindiujp@gmail.com>

### CODE REVIEW

**Comment by kpango** [comment]
where is the `project.clj` for leiningen??
I think it's better to configure for this project.

**Comment by kpango** [comment]
FYI: https://github.com/technomancy/leiningen/blob/stable/sample.project.clj

**Comment by kevindiu** [comment]
What do we need to configure for leiningen?

**Comment by kpango** [comment]
you can check it from sample project.clj above.

**Review by kpango — APPROVED** [review]
@kevindiu I'm really sorry, that I never knew about we already have settings for project.clj
https://github.com/vdaas/vald-client-clj/blob/master/project.clj
I think we don't need to fix project.clj

**Review by hlts2 — APPROVED** [review]

**Pull request merged**
